const StudentActionTypes = {
    GET_ALL_STUDENTS_START: 'GET_ALL_STUDENTS_START',
    GET_ALL_STUDENTS_SUCCESS: 'GET_ALL_STUDENTS_SUCCESS',
    GET_ALL_STUDENTS_FAILURE: 'GET_ALL_STUDENTS_FAILURE',
};

export default StudentActionTypes;
