const FacultyActionTypes = {
    GET_ALL_FACULTY_START: 'GET_ALL_FACULTY_START',
    GET_ALL_FACULTY_SUCCESS: 'GET_ALL_FACULTY_SUCCESS',
    GET_ALL_FACULTY_FAILURE: 'GET_ALL_FACULTY_FAILURE',
};

export default FacultyActionTypes;
