const SubjectActionTypes = {
    ADD_SUBJECT_START: 'ADD_SUBJECT_START',
    ADD_SUBJECT_SUCCESS: 'ADD_SUBJECT_SUCCESS',
    ADD_SUBJECT_FAILURE: 'ADD_SUBJECT_FAILURE',
    GET_ALL_SUBJECTS_START: 'GET_ALL_SUBJECTS_START',
    GET_ALL_SUBJECTS_SUCCESS: 'GET_ALL_SUBJECTS_SUCCESS',
    GET_ALL_SUBJECTS_FAILURE: 'GET_ALL_SUBJECTS_FAILURE',
};

export default SubjectActionTypes;
