const departmentActionTypes = {
    GET_ALL_DEPARTMENT_START: 'GET_ALL_DEPARTMENT_START',
    GET_ALL_DEPARTMENT_SUCCESS: 'GET_ALL_DEPARTMENT_SUCCESS',
    GET_ALL_DEPARTMENT_FALURE: 'GET_ALL_DEPARTMENT_FALURE',
};

export default departmentActionTypes;
