const UserActionTypes = {
    // LOGIN
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    // LOGOUT
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    // SET USER
    SET_IS_STUDENT: 'SET_IS_STUDENT',
    SET_IS_FACULTY: 'SET_IS_FACULTY',
};

export default UserActionTypes;
